blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('register/',views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('users/<int:user_id>/', views.view_profile, name='view_profile'),
    path('users/<int:user_id>/edit_profile/', views.edit_profile, name='edit_profile'),
    path('create_post/',views.create_post, name='create_post'),
    path('<int:post_id>/create_comment/',views.create_comment, name='create_comment'),
]

blog/templates/blog/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <p>Content:</p>{{ form.content }}<br>
        <input type="submit" value="Submit" />
    </form>
    <a href="{% url 'blog:index' %}">Back to index</a><br>
</body>
</html>

blog/templates/blog/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <p>Title: </p><br>{{ form.title }}<br>
        <p>Content: </p><br>{{ form.content }}<br>
        <input type="submit" value="Submit" />
    </form>
    <a href="{% url 'blog:index' %}">Back to index</a><br>
</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />

</head>
<body>
    <h1>{{ post.title }}, {{ post.author }}</h1>
    <p style="font-size: 24px">{{ post.body }}</p>
    {% if comment_list %}
        <ol class="comment">
            {% for c in comment_list %}
                <li><a href="{% url 'blog:view_profile' c.author_id %}">{{ c.author }}</a>: {{ c.body }}</li>
            {% endfor %}
        </ol>
    {% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'blog:create_comment' post.id %}">Create comment</a><br>
    {% endif %}
    <a href="{% url 'blog:index' %}">Back to index</a>
</body>
</html>

blog/templates/blog/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ user.username }}, you are editing your profile</h1><hr>
    <form action="" method="post">
        {% csrf_token %}
        <p>Sex: <p>{{ form.sex }}<br>
        <p>Age: </p>{{ form.age }}<br>
        <p>Self-introduction: </p>{{ form.introduction }}<br>
        <input type="submit" value="Submit" /><br>
        <a href="{% url 'blog:index' %}">Back to index</a><br>
    </form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />

</head>
<body>
    <h1>Post List</h1>
    <hr>
    {% if request.user.is_authenticated %}
        <h2>Hello! {{ user.username }}</h2>
        <a href="{% url 'blog:logout' %}">Logout</a><br>
        <a href="{% url 'blog:create_post' %}">Create a new post</a><br>
        <a href="{% url 'blog:view_profile' user.id %}">View My Profile</a><br>
    {% else %}
        <a href="{% url 'blog:login' %}">Login</a><br>
        <a href="{% url 'blog:register' %}">Register</a>
    {% endif %}

    {% if post_list %}
        <ul>
        {% for post in post_list %}
            <li class="post_list"><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
</body>
</html>

blog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <p>Username: </p>{{ form.username }}<br>
        <p>Password: </p>{{ form.password }}<br><br>
        <input type="submit" value="Login" />
    </form>
</body>
</html>

blog/templates/blog/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />
</head>
<body>
    <h1>{{ user.username }}'s Profile</h1><hr>
    {% if not profile.have_edited %}
        <p>This profile have not been edited!</p>
    {% endif %}
    <p>Days Joined: {{ days_joined }}</p>
    <p>Sex: {{ profile.sex }}</p>
    <p>Age: {{ profile.age }}</p>
    <p style="width: 30%">Self-introduction: {{ profile.introduction }}</p><br>
    {% if request.user.id == user.id %}
        <a href="{% url 'blog:edit_profile' user.id %}">Edit</a><br>
    {% endif %}
    <a href="{% url 'blog:index' %}">Back to index</a><br>
    {% if message %}
        <br>
        <strong>You cannot edit the profile of the others!</strong><br>
    {% endif %}
    {% if success %}
        <strong>Updated succeed!</strong>
    {% endif %}
</body>
</html>

blog/templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}" />
</head>
<body>
    <form action="" method="post">
        {{ error_message }}
        {% csrf_token %}
        <p>Username: </p>{{ form.username }}<br>
        <p>Password: </p>{{ form.password }}<br>
        <p>Email:</p>{{ form.email }}<br><br>
        <input type="submit" value="Register" />
    </form>
    <a href="{% url 'blog:index' %}">Back to index</a><br>
</body>
</html>